global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'localhost:9093'

rule_files:
  - 'alert_rules.yml'

scrape_configs:
  - job_name: 'ec2_instances'
    ec2_sd_configs:
      - region: us-west-2
        access_key: ******************
        secret_key: ******************
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance